#!/usr/bin/env bash
set -e

SKILLS_DIR="$HOME/.claude/skills"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RULES_DIR="$HOME/.claude/rules"

echo "Installing claude-skills to $SKILLS_DIR..."

mkdir -p "$SKILLS_DIR"
mkdir -p "$RULES_DIR"

# Skills are installed flat into ~/.claude/skills/<skill-name>/
# regardless of the category structure in this repo.
# Claude Code discovers skills one level deep only.

cp -r "$SCRIPT_DIR/context-handoff"                        "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/granola-tool-routing"                   "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/jira-pe-tickets"                        "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/meeting-prep"                           "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/skills-repo"                            "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/skill-creator"                          "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/architecture-decision"        "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/browser-extension-scaffold"   "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/code-review"                  "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/stack-decision"               "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/js-to-ts"                     "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/test-writer"                  "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/standards-check"              "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/standards-create"             "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/technical-spike"              "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/data-modeling"                "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/infrastructure-scaffold"      "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/infrastructure-review"        "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/mcp-manager"                  "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/dbt-modeler"                  "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/docs-audit"                   "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/developer/vendor-comparison"            "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/product-manager/design-critique"        "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/product-manager/feature-ideation"       "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/product-manager/feature-prioritization" "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/product-manager/requirements-doc"       "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/product-manager/ticket-creator"         "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/product-manager/ticket-review"          "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/product-manager/ticket-status"         "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/product-manager/researcher"             "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/product-manager/research-review"        "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/product-manager/user-story-flow"        "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/product-manager/discovery-doc"          "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/hiring/candidate-comparison"            "$SKILLS_DIR/"
cp -r "$SCRIPT_DIR/hiring/interview-debrief"               "$SKILLS_DIR/"

cp "$SCRIPT_DIR/CLAUDE_SHARED.md" "$RULES_DIR/CLAUDE_SHARED.md"
cp "$SCRIPT_DIR/CODER_RULES.md"  "$RULES_DIR/CODER_RULES.md"

echo "Done. Skills installed to $SKILLS_DIR:"
echo ""
echo "  context-handoff"
echo "  granola-tool-routing"
echo "  jira-pe-tickets"
echo "  meeting-prep"
echo "  skills-repo"
echo "  skill-creator"
echo "  architecture-decision"
echo "  browser-extension-scaffold"
echo "  code-review"
echo "  stack-decision"
echo "  js-to-ts"
echo "  test-writer"
echo "  standards-check"
echo "  standards-create"
echo "  technical-spike"
echo "  data-modeling"
echo "  infrastructure-scaffold"
echo "  infrastructure-review"
echo "  mcp-manager"
echo "  dbt-modeler"
echo "  docs-audit"
echo "  vendor-comparison"
echo "  design-critique"
echo "  feature-ideation"
echo "  feature-prioritization"
echo "  requirements-doc"
echo "  ticket-creator"
echo "  ticket-review
  ticket-status"
echo "  researcher"
echo "  research-review"
echo "  user-story-flow"
echo "  discovery-doc"
echo "  candidate-comparison"
echo "  interview-debrief"
echo ""
echo "Shared rules installed to $RULES_DIR/CLAUDE_SHARED.md and $RULES_DIR/CODER_RULES.md"
echo ""
echo "Skills are active in all Claude Code sessions."
echo "See README.md for customization instructions."
